name: base_project
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  image_picker: ^0.8.5+3
  photo_view: ^0.14.0
  image_cropper: ^3.0.0
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  get_it: ^7.2.0
  fluttertoast: ^8.0.9
  flutter_svg: ^1.1.3
  flutter_local_notifications: ^9.7.0
  cached_network_image: ^3.2.1
  google_fonts: ^3.0.1
  # easy_localization: ^3.0.1
  device_info_plus: ^4.1.0
  connectivity_plus: ^2.3.6+1
  flutter_image_compress: ^1.1.1
  # firebase_core: ^1.20.1
  # firebase_messaging: ^12.0.2
  
  # share_plus: ^4.0.10+1
  # url_launcher: ^6.1.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.10.0
  change_app_package_name: ^1.1.0



# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/icon/meri_sehat_icon.png"
#   remove_alpha_ios: true  

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/vector/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

